---

- name: install sublime
  hosts: local
  gather_facts: yes
  vars:
    makepkg_nonroot_user: "{{ ansible_ssh_user }}"
  tasks:
      
    - name: Get Download URL
      shell: curl https://www.sublimetext.com/3 | grep "Ubuntu 64 bit" | grep -Eo 'http[a-z0-9\:/\._]+\.tar\.bz2'
      register: sublimeurl
      
    - name: Download Sublime
      get_url: url={{ sublimeurl.stdout  }} dest=/tmp/sublime_text_3.tar.bz2

    - name: Unzip Syblime
      unarchive: src=/tmp/sublime_text_3.tar.bz2 dest={{ ansible_env.HOME }}/.local/ copy=no

    - name: Download Sublime Packages
      get_url: url="{{item}}" dest="{{ ansible_env.HOME }}/.local/sublime_text_3/Packages/"
      with_items:
        - https://packagecontrol.io/Package Control.sublime-package
