---

- name: install sublime
  hosts: local
  gather_facts: yes
  vars:
    makepkg_nonroot_user: "{{ ansible_ssh_user }}"
  tasks:
    - name: Download Sublime
      get_url: url=https://download.sublimetext.com/sublime_text_3_build_3114_x64.tar.bz2 dest=/tmp/

    - name: Unzip Syblime
      unarchive: src=/tmp/sublime_text_3_build_3114_x64.tar.bz2 dest={{ ansible_env.HOME }}/.local/ copy=no

    - name: Download Sublime Packages
      get_url: url="https://packagecontrol.io/Package Control.sublime-package" dest={{ ansible_env.HOME }}/.local/sublime_text_3/Packages/