---

- hosts: local

  strategy: free

  tasks:

   - name: install packages for ansible support
     register: pre_init_0
     shell: dnf -y install python python-dnf
     become: yes
     become_user: root
     become_method: su

   - name: add non-free repos
     register: pre_init_1
     when: pre_init_0|success
     become: yes
     become_user: root
     become_method: su
     dnf:
         name: "{{ item }}"
         state: installed
         disable_gpg_check: yes
     with_items:
         - "http://rpm.livna.org/livna-release.rpm"
         - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm"
         - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm"

   - name: upgrade system
     register: pre_init
     when: pre_init_1|success
     become: yes
     become_user: root
     become_method: su
     dnf: name=* state=latest disable_gpg_check=yes

   - name: Base Libs Installing
     register: init
     when: pre_init|success
     become: yes
     become_user: root
     become_method: su
     dnf: name={{ item  }} state=installed
     with_items:
      - httpd
      - openssl-devel
      - openssl-libs
      - tmux
      - vim
      - python3
      - python3-devel
      - python
      - python-devel
      - gcc-c++
      - libffi-devel
      - libyaml
      - libyaml-devel
      - patch
      - postgresql
      - postgresql-libs
      - postgresql-devel
      - postgresql-server
      - postgresql-static
      - postgresql-plpython
      - postgresql-plpython3
      - python-psycopg2
      - libxml2-devel
      - libxslt-devel
      - redis
      - keepassx
      - kernel-devel
      - kernel-headers
      - kernel-modules
      - kernel-modules-extra
      - kernel-tools
      - kernel-tools-libs
      - curl
      - zeromq
      - zeromq-devel
      - libpng
      - libpng-devel
      - libjpeg-turbo
      - libjpeg-turbo-devel
      - sqlite
      - sqlite-devel
      - sqlite-libs
      - rpm-build 
      - cabextract 
      - ttmkfdir 
      - wget
      - zlib
      - zlib-devel
# media deps
      - gstreamer-plugins-ugly 
      - gstreamer-plugins-bad
      - libdvdread 
      - libdvdcss 
      - libdvdnav 
      - gstreamer-plugins-ugly 
      - gstreamer-plugins-bad 
      - gstreamer-plugins-ugly  
      - audacious-plugins-freeworld-mp3
# other
      - fish


   - name: Initiate database
     command: service postgresql initdb
              creates=/var/lib/pgsql/data/postgresql.conf

   - name: Start PostgreSQL and enable at boot
     service: name=postgresql
              enabled=yes
              state=started

   - name: Ensure PostgreSQL is listening on all localhost
     lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
       regexp='^#?listen_addresses\s*='
       line="listen_addresses = '127.0.0.1'"
       state=present
     notify: restart postgresql


   - lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                 regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
                 line='host all all 127.0.0.1/32 md5'
                 insertbefore=BOF
     notify: restart postgresql


   # -  postgresql_user:
   #      name: "{{ ansible_env.USERNAME }}"
   #      password: qwerty
   #      role_attr_flags: SUPERUSER


   - name: Start Redis and enable at boot
     service: name=redis
              enabled=yes
              state=started



  handlers:
   - name: restart postgresql
     service: name=postgresql state=restarted

